ecommerce1/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls")),
]
handler404 ="myapp.views.error_404_view"

myapp/urls.py
from unicodedata import name
from xml.sax import handler
from django import views
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings;
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index, name="index"),
    path('admin_login/',views.admin_login, name="login"),
    path('check/',views.check, name="check"),
    path('dashboard/',views.dashboard, name="admindashboard"),
    path('productdetails', views.details, name="product_details"),
    path('subcat_list', views.subcat_list, name="subcategory_product_view"),
    path("all_subcategory/",views.all_subcategory, name="all_subcategory"),

    # CATEGORY MANAGEMENT
    path('categorymanage/',views.categorymanage,name='categorymanage'),
    path('add/',views.addcat, name='add_category'),
    path('delete',views.cat_delete, name='category_delete'),
    path('edit',views.cat_edit, name='edit_category'),
    path('update/', views.cat_update, name="update"),

    # SUB-CATEGORY MANAGEMENT
    path('submanage/',views.submanage,name='submanage'),
    path('sub_add/',views.add_subcat, name='add_subcategory'),
    path('delete_sub',views.subcat_delete, name='subcategory_delete'),
    path('edit_sub',views.subcat_edit, name='edit_subcategory'),
    path('subupdate/', views.subcat_update, name="update"),

    #PRODUCT
    path('addproduct/',views.addproduct,name='addproduct'),
    path('additem/',views.additem,name="additem"),
    path('deleteproduct/',views.deleteproduct, name='deleteproduct'),
    path('productdata',views.productdata,name='productdata'),

    #CARD
    path('addingitem',views.addingitem,name='addingitem'),
    path('addtocart',views.addtocart,name='addtocart'),
    path('deletecart',views.deletecart,name='deletecart'),

    #CHECKOUT
    path('checkout/',views.checkout,name='checkout'),

    #ORDER
    path('order/',views.order,name='order'),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 ="myapp.views.error_404_view"

myapp/models.py
from django.db import models
from numpy import product
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Login(models.Model):
    email= models.CharField(max_length=50)
    password=models.CharField(max_length=50)

class Category(models.Model):
    category_name=models.CharField(max_length=50)
    def __str__(self):
        return self.category_name

class Sub_Category(models.Model):
    subcatname=models.CharField(max_length=50);
    category=models.ForeignKey(Category,on_delete=models.CASCADE);
    def __str__(self):
        return self.subcatname;

class Product(models.Model):
    category= models.ForeignKey(Category, on_delete=models.CASCADE, null=False, default="")
    subcategory= models.ForeignKey(Sub_Category, on_delete=models.CASCADE, null=False, default="")
    image=models.ImageField(upload_to="ecommerceimg/productimg")
    name=models.CharField(max_length=100)
    price=models.IntegerField()
    no=models.IntegerField(default=0,null=True)
    sku_id=models.CharField(max_length=100,default=0,null=True )
    def __str__(self):
        return self.name

class Card(models.Model):
    product_id = models.IntegerField()
    

class Buy(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    phone = PhoneNumberField(unique = True, null = False, blank = False)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    zip = models.CharField(max_length=10)
    product_name = models.CharField(max_length=50)
    product_quantity = models.IntegerField()
    product_price = models.IntegerField(default=0,null=False)
    total = models.IntegerField(default=0,null=False)

templates/addtocart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.css" rel="stylesheet" />
    <title>Document</title>
</head>

<body>

    <section class="h-100" style="background-color: #eee;">
        <form method="post" action="/checkout/">
            {% csrf_token %}
        <div class="container h-100 py-5">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-10">

                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
                        <div>
                            <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!"
                                    class="text-body">price <i class="fas fa-angle-down mt-1"></i></a></p>
                        </div>
                    </div>
                        
                    <div class="card rounded-3 mb-4">
                        <div class="card-body p-4">

                            {% if count_data %}
                            {% for product in product_data %}
                            {% for products in product %}
                            <div class="row d-flex justify-content-between align-items-center">
                                <div class="col-md-2 col-lg-2 col-xl-2">
                                    <img src="{{products.image}}"
                                        class="img-fluid rounded-3" alt="Cotton T-shirt">
                                </div>
                                <div class="col-md-3 col-lg-3 col-xl-3">
                                    <input class="lead fw-normal mb-2 border-0" name="pname" value="{{products.name}}" readonly  />
                                </div>
                                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                    <button class="btn btn-link px-2" type="button"
                                        onclick="sub({{products.id}})" id="sub_button{{products.id}}">
                                        <i class="fas fa-minus"></i>
                                    </button>

                                        <input id="{{products.id}}" min="0" name="quantity" value="1" type="number" readonly
                                        class="form-control form-control-sm" />

                                        <input id="hid{{products.id}}" type="hidden" value="{{products.price}}" />

                                    <button class="btn btn-link px-2" type="button"
                                        onclick="add({{products.id}})">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                    
                                </div>
                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                    <input id="pr{{products.id}}" class="pricedata border-0"  name="price" value="{{products.price}}"/ readonly>
                                </div>
                                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                    <a href="/deletecart?details_id={{products.id}}" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
                                </div>
                            </div>
                            {% endfor %}
                            {% endfor %}
                        </div>
                    </div>
                    <input type="hidden" value="{{count_data}}" id="product_length">
                    {% endif %}


                    <div class="d-flex justify-content-between align-items-center mb-4 ">
                        <h3 class="fw-bold mb-0 text-black ">TOTAL INR:</h3>
                    
                            <!-- <span style="font-size:20px ;">RS</span><input type="number" id="total" style="padding: 5px; font-size: large; text-align: left;"; readonly> -->
                        <div>
                            <span style="font-size: 30px ;" class="fw-bold text-black" >RS :</span>
                            <input style="font-size: 30px ;" class="fw-bold text-black border-0 bg-transparent r-0" name="total" id="total" readonly/>
                        </div>
                    </div>


                    <div class="card">
                        <div class="card-body mb-0">
                            <input type="submit" class="btn btn-primary btn-block btn-lg" value="Proceed To Checkout" />
                            <a href="/" class="btn btn-warning btn-block btn-lg">Continue Shopping</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </form>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
        function add(id){
            let newarr = [];
            let data = 0
            let count = parseInt(document.getElementById(`${id}`).value)
            count = count +1 
            document.getElementById(`${id}`).value=count
            const price = Number(document.getElementById(`hid${id}`).value);
            total = count * price;
            document.getElementById(`pr${id}`).value = total;
            document.getElementById(`sub_button${id}`).disabled=false
            $(document).ready(function(){
            $(".pricedata").each(function(){
                newarr.push($(this.value));
            })
            for(let i=0; i<newarr.length; i++){
                data += (Number(newarr[i].selector));
            }
                document.getElementById("total").value = data
        });
        } 
        function sub(id){
            let newarr = [];
            let data = 0
            let count = parseInt(document.getElementById(`${id}`).value)
            if(count <=1 ){
                document.getElementById(`sub_button${id}`).disabled=true
            }
            else{
                count = count - 1
                document.getElementById(`${id}`).value=count
                const price = Number(document.getElementById(`hid${id}`).value);
                total = count * price;
                document.getElementById(`pr${id}`).value = total;
                $(document).ready(function(){
                $(".pricedata").each(function(){
                    newarr.push($(this.value));
                })
                for(let i=0; i<newarr.length; i++){
                    data += (Number(newarr[i].selector));
                }
                document.getElementById("total").value = data
            });
            }
        } 
        let newarr1 = []
        $(document).ready(function(){
            let data = 0
            $(".pricedata").each(function(){
                newarr1.push($(this.value));
            })
            console.log(newarr1)
            for(let i=0; i<newarr1.length; i++){
                data += (Number(newarr1[i].selector));
            }
            console.log(data)
            document.getElementById("total").value = data
        });
       

    </script>
</body>

</html>

templates/all_subcategory.html
{% extends "master.html" %}
{% load static %}
{% block body %}
 <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>

                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        {% for category in categorydata %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#{{category.id}}">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        {{category.category_name}}
                                    </a>
                                </h4>
                            </div>
                            <div id="{{category.id}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul>
                                {% for y in category.sub_category_set.all  %}    
                                        <li><a href="/subcat_list?subcatid={{y.id}}">{{y.subcatname}} </a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div><!--/category-products-->
                    
                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well text-center">
                             <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                             <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->
                    
                    <div class="shipping text-center"><!--shipping-->
                        <img src="{% static 'images/home/shipping.jpg' %}" alt="" />
                    </div><!--/shipping-->
                
                </div>
            </div>
            
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Features Items</h2>
                    {% for  products in subcategorylist %}
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                    <div class="productinfo text-center">
                                        <img src="{{products.image}}" alt="" height="250" />
                                        <h2>{{products.price}}</h2>
                                        <p>{{products.name}}</p>
                                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                    </div>
                                    <div class="product-overlay">
                                        <div class="overlay-content">
                                            <a class="btn btn-info" href="/productdetails?details_id={{products.id}}">Visit</a>
                                            <h2>{{products.price}}</h2>
                                            <p>{{products.name}}</p>
                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                        </div>
                                    </div>
                            </div>
                            <div class="choose">
                                <ul class="nav nav-pills nav-justified">
                                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div><!--features_items-->
            </div>
        </div>
 </div>
 
{% endblock %}

templates/checkout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>Check-Out</title>
</head>

<body>

  <div class="container">
    <div class="text-center fs-4">BILLING FORM</div>
    <div class="row mx-0 justify-content-around">
      <div class="col-sm-5">
        <form method="POST" class="w-100 rounded p-4 border bg-white" action="/order/">
          {% csrf_token %}
          <label class="d-block mb-1">
            <span class="d-block mb-1">Name</span>
            <input name="name" type="text" class="form-control" />
          </label>

          <label class="d-block mb-1">
            <span class="d-block mb-1">Email</span>
            <input name="email" type="text" class="form-control" placeholder="" />
          </label>

          <label class="d-block mb-1">
            <span class="d-block mb-1">Phone</span>
            <input name="phone" type="tel" class="form-control" placeholder="" />
          </label>

          <label class="d-block mb-1">
            <span class="d-block mb-1">State</span>
            <input name="state" type="text" class="form-control" placeholder="" />
          </label>

          <label class="d-block mb-1">
            <span class="d-block mb-1">City</span>
            <input name="city" type="text" class="form-control" placeholder="" />
          </label>

          <label class="d-block mb-1">
            <span class="d-block mb-1">Address line </span>
            <input name="address" type="text" class="form-control" placeholder="" />
          </label>

          <label class="d-block mb-1">
            <span class="d-block mb-1">Zip/Postal code</span>
            <input name="zip" type="text" class="form-control" placeholder="" />
          </label>

          <!-- <div class="mb-3">
                <button type="submit" class="btn btn-primary px-3">Save</button>
              </div> -->

       
      </div>
      <div class="col-sm-6 border h-auto ">
        <div class="text-center">PRODUCTS</div>
        <table class="table border">
          <tr class="alert alert-info">
            <td>Product</td>
            <td>Quantity</td>
            <td>Price</td>
          </tr>

          <tr>
            <td> {% for nam in name %}
              <input type="text" value="{{nam}}" name="pname" class="col-sm-9 mt-2 d-flex flex-column text-center" readonly />
              {% endfor %}
            </td>


            <td>{% for quan in quantity %}
              <input type="number" value="{{quan}}" name="pquantity" class="col-sm-5 d-flex flex-column mt-2  text-center" readonly />
              {% endfor %}
            </td>


            <td>{% for price in price %}
              <input type="text" value="{{price}}" name="pprice" class="col-sm-4 d-flex flex-column mt-2  text-center" readonly />
              {% endfor %}
            </td>
          </tr>
        </table>
        <div class="row justify-content-between">
          <div class="col-sm-3 text-center">
            <h5>TOTAL</h5>
          </div>
          
          <div class="col-sm-4">
              {% if total %}
              <input type="number" class="fw-bold border-0 p-1" name="total" value="{{total}}" readonly />
              {% endif %}
            </div>
        </div>
        <input type="submit" class="mt-2 btn btn-primary w-100 fs-4" value="Place Your Order">
      </div>
    </form>
    </div>
  </div>
  </div>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
  <section class="vh-100">
    <div class="container py-5 h-100">
      <h1 class="text-center alert alert-primary">Admin Login</h1>
      <div class="row d-flex align-items-center justify-content-center h-100">
        <div class="col-md-8 col-lg-7 col-xl-6">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
            class="img-fluid" alt="Phone image">
        </div>
        <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
          <form action="/check/" method="post">
            {% csrf_token %}
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" id="form1Example13" name="uemail" class="form-control form-control-lg" />
              <label class="form-label" for="form1Example13">Email address</label>
            </div>
  
            <!-- Password input -->
            <div class="form-outline mb-4">
              <input type="password" id="form1Example23" name="upass" class="form-control form-control-lg" />
              <div class="d-flex justify-content-between mb-4">
                <label class="form-label" for="form1Example23">Password</label>
                <a href="#!" class="mr-0">Forgot password?</a>
              </div>
            </div>
            
  
            <!-- Submit button -->
            <button type="submit" class="btn btn-success btn-lg btn-block">Login</button>
            <button class="btn btn-primary btn-lg btn-block">Register</button>
  
            <div class="divider d-flex align-items-center my-4">
              <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
            </div>
  
            <a class="btn btn-primary btn-lg btn-block" style="background-color: #3b5998" href="#!"
              role="button">
              <i class="fab fa-facebook-f me-2"></i>Continue with Facebook
            </a>
            <a class="btn btn-primary btn-lg btn-block" style="background-color: #55acee" href="#!"
              role="button">
              <i class="fab fa-twitter me-2"></i>Continue with Twitter</a>
  
          </form>
        </div>
      </div>
    </div>
  </section>
</body>
</html>


  <!-- 
    <div class="container">
        <h1 class="text-center alert alert-info text-white">Login Page</h1>
         <form action="/check/" method="post">
                  {% csrf_token %}
                    <div class="form-outline mb-4">
                      <label class="form-label" for="form3Example3cg">Your Email</label>
                      <input type="email" id="form3Example3cg" name="uemail" class="form-control form-control-lg" />
                    </div>
    
    
    
                    <div class="form-outline mb-4">
                      <label class="form-label" for="form3Example4cg">Password</label>
                      <input type="password" id="form3Example4cg" name="upass" class="form-control form-control-lg" />
                    </div>
    
                    
    
                    <div class="d-flex justify-content-center">
                      <input type="submit" class="btn btn-primary" value="Login">
    
                  </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
   -->

templates/pagenotfound.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Page Not Found</h1>
    <p>You hit wrong URL</p>
</body>
</html>